- name: create ec2 and route 53 records
  hosts: local
  var_files:
  - vars.yaml
  instances:
  - mysql
  - backend
  - frontend
  zone: aathidya.online
  task:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip3.9:
     name:
       - boto3
       - botocore
     executable: pip3.9
  - name: create ec2 instances
    amazon.aws.ec2_instances:
      name: "{{}}"
      vpc_subnet_id: "{{}}"
      instance_type: "t3.micro"
      security_group: "{{}}"
      image_id: "{{ }}"  
    loop: "{{ instances }}"
    register: ec2_instances     