- name: create ec2 and route 53 records
  hosts: local
  vars_files:
  - vars.yaml
  vars:
    zone: aathidya.online
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
     name:
       - boto3
       - botocore
     executable: pip3.9
  - name: create ec2_instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ SUBNET_ID }}"
      instance_type: "t3.micro"
      security_group: "{{ SG_ID}}"
      image_id: "{{ AMI_ID}}"  
    loop: 
    - mysql
    - backend
    - frontend
    register: ec2_instances  
  - name: print the output
    ansible.builtin.debug:
      msg: " {{ ec2_instances }}"     


    #private IP R53
  - name: create r53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.aathidya.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: create r53 public record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #aathidya.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend" #when keyword should n    