- name: create ec2 and route 53 records
  hosts: local
  vars_files:
  - vars.yaml
  vars:
    zone: aathidya.online
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
     name:
       - boto3
       - botocore
     executable: pip3.9
  - name: create ec2_instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ SUBNET_ID }}"
      instance_type: "t3.micro"
      security_group: "{{ SG_ID}}"
      image_id: "{{ AMI_ID}}"  
    loop: 
    - mysql
    - backend
    - frontend
    register: ec2_instances  
  - name: print the output
    ansible.builtin.debug:
      mes: " {{ ec2_instances }}"     